### ISSUE TITLE
Hadoop Error On Startup

### ISSUE THREAD

**Issue by ckdarby** [riskfocus/helm-charts-public#8]
When starting the helm the job manager complains in the k logs of some issues related to hadoop.

```text
2020-04-28 19:09:05,604 WARN  org.apache.hadoop.util.NativeCodeLoader                       - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

2020-04-28 19:09:05,730 ERROR org.apache.flink.runtime.security.modules.HadoopModuleFactory  - Cannot create Hadoop Security Module.
java.lang.NoClassDefFoundError: org/apache/hadoop/hdfs/HdfsConfiguration
	at org.apache.flink.runtime.security.modules.HadoopModuleFactory.createModule(HadoopModuleFactory.java:50)
	at org.apache.flink.runtime.security.SecurityUtils.install(SecurityUtils.java:64)
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.installSecurityContext(ClusterEntrypoint.java:200)
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.startCluster(ClusterEntrypoint.java:166)
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.runClusterEntrypoint(ClusterEntrypoint.java:518)
	at org.apache.flink.runtime.entrypoint.StandaloneSessionClusterEntrypoint.main(StandaloneSessionClusterEntrypoint.java:64)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.hdfs.HdfsConfiguration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 6 more

```

**Comment by SkyGra** [comment]
hi, have you solved this problem? I also encounterd this.

**Comment by ckdarby** [comment]
@SkyGra No but it didn't cause us any issues when we were using this chart.

**Comment by SkyGra** [comment]
@ckdarby yeah, me too. it seems have no side effect .

**Comment by wolfgang1219** [comment]
I have the same problem

**Comment by danielchang-Z** [comment]
I have the same problem too.

**Comment by vasilescur** [comment]
+1

**Comment by aoterolorenzo** [comment]
Having same problem too. Trying to use Minio S3 as a storage service to implement high availability, using the hadoop plugin and configured storageDir and HA parameters, although the above error seems unimportant, can't get s3 working (minio don't receive a single package from Flink), so I think that this is related. Also I'm having other issues with base and presto plugins, java related too:

```
java.util.ServiceConfigurationError: org.apache.flink.core.fs.FileSystemFactory: 
org.apache.flink.fs.s3hadoop.S3FileSystemFactory Unable to get public no-arg constructor
```
